[workspace]
members = [
    "crates/*",
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha.2"
authors = ["Benedikt Schwab <benedikt.schwab@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/envis-space/ecoord"

[workspace.dependencies]
clap = "4.5.8"
thiserror = "1.0.61"
serde = "1.0.203"
serde_json = "1.0.120"
zstd = "0.13.1"
nalgebra = "0.33.0"
chrono = "0.4.38"
itertools = "0.13.0"
indextree = "4.6.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
approx = "0.5.1"
num-traits = "0.2.19"
