[workspace]
members = [
    "crates/*",
]

[workspace.package]
version = "0.0.1-alpha.1"
authors = ["Benedikt Schwab"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tum-gis/ecoord"

[workspace.dependencies]
thiserror = "1.0.34"
serde = "1.0"
serde_json = "1.0"
zstd = "0.11"
nalgebra = "0.31.1"
chrono = "0.4.22"
itertools = "0.10.3"
indextree = "4.4.0"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
